name: Build App
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - .github/workflows/theseus-build.yml
      - 'apps/app/**'
      - 'apps/app-frontend/**'
      - 'packages/app-lib/**'
      - 'packages/assets/**'
      - 'packages/ui/**'
      - 'packages/utils/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build (${{ matrix.artifact-target-name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            artifact-target-name: universal-apple-darwin
          - platform: windows-latest
            artifact-target-name: x86_64-pc-windows-msvc
          - platform: ubuntu-24.04
            artifact-target-name: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
          target: ${{ contains(matrix.platform, 'macos') && 'x86_64-apple-darwin' || '' }}

      - name: Setup mold
        if: contains(matrix.platform, 'ubuntu')
        uses: rui314/setup-mold@v1

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install Linux build dependencies
        if: contains(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Setup Dasel
        uses: jaxxstorm/action-install-gh-release@v3
        with:
          repo: TomWright/dasel
          tag: v2.8.1
          extension-matching: disable
          rename-to: ${{ contains(matrix.platform, 'windows') && 'dasel.exe' || 'dasel' }}
          chmod: 0755

      - name: Set application version
        shell: bash
        run: |
          APP_VERSION="$(git describe --tags --always | sed -E 's/-([0-9]+)-(g[0-9a-fA-F]+)$/-canary+\1.\2/')"
          echo "Setting application version to ${APP_VERSION#v}"
          dasel put -f apps/app/Cargo.toml -t string -v "${APP_VERSION#v}" 'package.version'
          dasel put -f packages/app-lib/Cargo.toml -t string -v "${APP_VERSION#v}" 'package.version'
          dasel put -f apps/app-frontend/package.json -t string -v "${APP_VERSION#v}" 'version'
          cp packages/app-lib/.env.prod packages/app-lib/.env

      - name: Install dependencies
        run: pnpm install

      - name: Build app (unsigned)
        run: pnpm --filter=@modrinth/app run tauri build --config tauri-release.conf.json ${{ contains(matrix.platform, 'macos') && '--target universal-apple-darwin' || '' }}

      - name: Upload app bundles
        uses: actions/upload-artifact@v4
        with:
          name: App bundle (${{ matrix.artifact-target-name }})
          if-no-files-found: warn
          path: |
            target/release/bundle/appimage/Modrinthium_*.AppImage
            target/release/bundle/deb/Modrinthium_*.deb
            target/release/bundle/rpm/Modrinthium-*.rpm
            target/release/bundle/nsis/Modrinthium_*-setup.exe
            target/universal-apple-darwin/release/bundle/dmg/Modrinthium_*.dmg
